print("Hello world!")
print("What is your name?")
myname = input()
print("I’ve heard great things about, "+ myname)
mycolor = input("What is your favorite color? ")
print("oh, the same as Pikachu, Pikachu loves " + mycolor)